### ISSUE TITLE
How to check Giphy.recents is initialized?

### ISSUE THREAD

**Issue by truthhonestmessaging** [Giphy/giphy-android-sdk#122]
App is crashing if Giphy.recents is not initialized when I call Giphy.recents.clear()

I can't check it by doing standard way of Giphy::recents.isInitialized, because this throws error.

I just want to clear the Giphy cache when the user logs out of the app.

**Comment by ALexanderLonsky** [comment]
hey @truthhonestmessaging,
yes, you are right. you can't access this property before either `Giphy.configure` or `GiphyDialogFragment.newInstance(settings, YOUR_ANDROID_SDK_KEY)` is called.

`Giphy::recents.isInitialized` won't work because of this:

> This check is only available for the properties that are lexically accessible, when declared in the same type or in one of the outer types, or at top level in the same file.

And we don't provide now an option to check whether Giphy is initialized or not,  but you can do this on your own.

Also, as an option, you can intercept `UninitializedPropertyAccessException` with the`try-catch` block:

```
try {
    Giphy.recents.clear()
} catch (t: UninitializedPropertyAccessException) {}
```

**Comment by truthhonestmessaging** [comment]
Thank you, works perfectly. You can close this now!
