### ISSUE TITLE
Set query to GiphyDialogFragment

### ISSUE THREAD

**Issue by dazndrey** [Giphy/giphy-android-sdk#193]
I want to set a specific query on opening the GIPHY template. Seems like it's possible for iOS (with `giphy.showMoreByUser`), but I can't find something similar for Android.

Is it possible to set the search query or content on GiphyDialogFragment?

**Comment by ALexanderLonsky** [comment]
hey @dazndrey,
It is a bug rather than a feature on iOS :)
This functionality is not provided by `GiphyDialogFragment`.
The purpose of `giphy.showMoreByUser` is to narrow down the search results to a particular content creator.
In order to set a specific query, you will need to use our custom [GiphyGridView + GPHContent ](https://github.com/Giphy/giphy-android-sdk/blob/main/Docs.md#giphygridview-gphcontent) solution.
